name: 'Apply latest configuration to Fleet'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # allows manual triggering
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC

# Prevent concurrent runs of this workflow.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
permissions:
  contents: read

jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4

      - name: Apply latest configuration to Fleet
        uses: ./.github/gitops-action
        with:
          # Run GitOps in dry-run mode for pull requests.
          dry-run-only: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
          fleet-url: ${{ secrets.FLEET_URL }}
          fleet-api-token: ${{ secrets.FLEET_API_TOKEN }}
          fleet-global-enroll-secret: ${{ secrets.FLEET_GLOBAL_ENROLL_SECRET }}
          fleet-workstations-enroll-secret: ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET }}
          fleet-workstations-canary-enroll-secret: ${{ secrets.FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET }}
          fleet-engineering-enroll-secret: ${{ secrets.FLEET_ENGINEERING_ENROLL_SECRET }}
          fleet-new-hire-enroll-secret: ${{ secrets.FLEET_NEW_HIRE_ENROLL_SECRET }}